version: '2'

services:
  rest-server:
    build: 
      context: .
      dockerfile: Dockerfile
    ports:
      - 8080:8080
    volumes:
      - .:/home/joao-faria/Desktop/jerseytesting2
    stdin_open: true
    tty: true

